sonar.projectKey=krealalejo_hearthstone
sonar.organization=krealalejo

sonar.projectName=hearthstone
sonar.sourceEncoding=UTF-8

sonar.sources=app,server
sonar.tests=tests
sonar.exclusions=**/.nuxt/**,**/dist/**,**/node_modules/**,server/models/**,app/plugins/**,app/middleware/**,server/plugins/**,**/*.d.ts,app/pages/**,app/app.vue,app/types/**,app/composables/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.sonar.json
